title: Westview Hotels Staff Guidelines
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://mattgamer6660.github.io/WestviewHotelsGuide/
  
color_scheme: westview

callouts:
  warning:
    title: Warning
    color: red
  important:
    title: Important
    color: blue
logo: "logo.png"
favicon_ico: "favicon.ico"
